sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo-cli
- npm install
install:
- npm install
script:
- hexo clean
- hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: a1db580b64601c377bacf5e461f97a08b31d6064 
  keep-history: true
  on:
    branch: master
  local-dir: public
