sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo-cli
- npm install
install:
- npm install
script:
- hexo clean
- hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 31d13a4b75025f2dd4d6c42248c5b91377823b4f
  keep-history: true
  on:
    branch: master
  local-dir: public
